# Generated by Django 4.2.15 on 2025-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0013_2_9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='api_version',
            field=models.CharField(blank=True, default='2020-08-27', help_text='The API version events are rendered as for this webhook endpoint. Defaults to the configured Stripe API Version.', max_length=64),
        ),
    ]
